//
//  GenerateSceneConfigurator.swift
//  RandoN
//
//  Created by Mac on 03/06/2019.
//  Copyright (c) 2019 Lammax. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

class GenerateSceneConfigurator {
    // MARK: Object lifecycle
    
    static let sharedInstance = GenerateSceneConfigurator()
    
    private init() {}
    
    // MARK: Configuration
    
    func configure(viewController: GenerateSceneViewController) {
        let interactor = GenerateSceneInteractor()
        let presenter = GenerateScenePresenter()
        let router = GenerateSceneRouter()
        let worker = GenerateSceneWorker()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        interactor.worker = worker
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
}
