//
//  GenerateSceneModels.swift
//  RandoN
//
//  Created by Mac on 03/06/2019.
//  Copyright (c) 2019 Lammax. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum GenerateScene {
  // MARK: Use cases
  
    enum Unique {
        struct Request {
            let isUnique: Bool
        }
        struct Response {
        }
        struct ViewModel {
        }
    }
    
    enum Numbers {
        struct Request {
            let maybeFrom: String?
            let maybeTo: String?
            let maybeNums: String?
        }
        struct Response {
            let numbers: [Int]?
            let separator: String
        }
        struct ViewModel {
            let numbersString: String
        }
    }
    
}
