//
//  GenerateScenePresenter.swift
//  RandoN
//
//  Created by Mac on 03/06/2019.
//  Copyright (c) 2019 Lammax. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol GenerateScenePresentationLogic {
    func presentUnique(response: GenerateScene.Unique.Response)
    func presentNumbers(response: GenerateScene.Numbers.Response)
}

class GenerateScenePresenter: GenerateScenePresentationLogic {
    weak var viewController: GenerateSceneDisplayLogic?

    // MARK: Do something

    func presentUnique(response: GenerateScene.Unique.Response) {
        let viewModel = GenerateScene.Unique.ViewModel()
        viewController?.displayUnique(viewModel: viewModel)
    }
    
    func presentNumbers(response: GenerateScene.Numbers.Response) {
        var result: String = "No results"
        
        if let numbers = response.numbers {
            result = numbers.map({ String($0) }).joined(separator: response.separator)
        }

        let viewModel = GenerateScene.Numbers.ViewModel(numbersString: result)
        viewController?.displayNumbers(viewModel: viewModel)
    }
    
}
