//
//  GenerateSceneInteractor.swift
//  RandoN
//
//  Created by Mac on 03/06/2019.
//  Copyright (c) 2019 Lammax. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol GenerateSceneBusinessLogic
{
  func doSomething(request: GenerateScene.Something.Request)
}

protocol GenerateSceneDataStore
{
  //var name: String { get set }
}

class GenerateSceneInteractor: GenerateSceneBusinessLogic, GenerateSceneDataStore
{
  var presenter: GenerateScenePresentationLogic?
  var worker: GenerateSceneWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: GenerateScene.Something.Request)
  {
    worker = GenerateSceneWorker()
    worker?.doSomeWork()
    
    let response = GenerateScene.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
