//
//  GenerateSceneInteractor.swift
//  RandoN
//
//  Created by Mac on 03/06/2019.
//  Copyright (c) 2019 Lammax. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol GenerateSceneBusinessLogic {
    func saveUnique(request: GenerateScene.Unique.Request)
    func calcNumbers(request: GenerateScene.Numbers.Request)
}

protocol GenerateSceneDataStore {
    var isUnique: Bool { get set }
}

class GenerateSceneInteractor: GenerateSceneBusinessLogic, GenerateSceneDataStore {
    
    var presenter: GenerateScenePresentationLogic?
    var worker: GenerateSceneWorker?
    
    //MARK: DataStore
    var isUnique: Bool = true
  
    // MARK: Do stuff

    func saveUnique(request: GenerateScene.Unique.Request) {
        self.isUnique = request.isUnique
        let response = GenerateScene.Unique.Response()
        presenter?.presentUnique(response: response)
    }
    
    func calcNumbers(request: GenerateScene.Numbers.Request) {
        let response = GenerateScene.Numbers.Response(
            numbers: self.worker?.calcRandomNumbers(model: request, isUnique: self.isUnique),
            separator: " "
        )
        presenter?.presentNumbers(response: response)
    }
    
}
