//
//  GenerateScenePresenter.swift
//  RandoN
//
//  Created by Mac on 03/06/2019.
//  Copyright (c) 2019 Lammax. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol GenerateScenePresentationLogic
{
  func presentSomething(response: GenerateScene.Something.Response)
}

class GenerateScenePresenter: GenerateScenePresentationLogic
{
  weak var viewController: GenerateSceneDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: GenerateScene.Something.Response)
  {
    let viewModel = GenerateScene.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
